// <auto-generated />
namespace TasteFoodItx.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class productcontextekledim : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productcontextekledim));
        
        string IMigrationMetadata.Id
        {
            get { return "202605212018284_productcontextekledim"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
