// <auto-generated />
namespace TasteFoodItx.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class mig4IconCircleColorColumnAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig4IconCircleColorColumnAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202606021942130_mig4IconCircleColorColumnAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
