// <auto-generated />
namespace TasteFoodItx.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class mig7SliderClassAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig7SliderClassAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202606032054455_mig7SliderClassAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
